import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from 'react-hot-toast'
import { Suspense } from "react";
import Load from "@/components/load";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "generate your cv made by smn",
  description: "Generated by md riasad azim sifat",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="">
      <body className={inter.className}>
      <Toaster />
        <Suspense  fallback={<div className="w-full h-screen flex justify-center items-center"><Load /></div>} >
        {children}
        </Suspense>
        </body>
    </html>
  );
}
